apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: joplin-postgres-pvc
  namespace: joplin
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-cluster
  resources:
    requests:
      storage: 3Gi