# Volume definitions
---
apiVersion: longhorn.io/v1beta2
kind: Volume
metadata:
  name: pvc-f167fbcd-c0f1-4ee6-b1fe-a28545cf8d53
  namespace: longhorn
spec:
  diskSelector: []
  frontend: blockdev
  nodeSelector: []
  numberOfReplicas: 3
  size: "21474836480"
  staleReplicaTimeout: 30
---
apiVersion: longhorn.io/v1beta2
kind: Volume
metadata:
  name: pvc-cf13638f-9c98-42c8-b793-ac30af2b23a5
  namespace: longhorn
spec:
  diskSelector: []
  frontend: blockdev
  nodeSelector: []
  numberOfReplicas: 3
  size: "1073741824"
  staleReplicaTimeout: 30
---
apiVersion: longhorn.io/v1beta2
kind: Volume
metadata:
  name: pvc-42ed8396-1067-4c2b-804a-24341e24b4a6
  namespace: longhorn
spec:
  diskSelector: []
  frontend: blockdev
  nodeSelector: []
  numberOfReplicas: 3
  size: "10737418240"
  staleReplicaTimeout: 30
---
apiVersion: longhorn.io/v1beta2
kind: Volume
metadata:
  name: pvc-fcfe2a57-e255-4d5b-a366-fb0f64098371
  namespace: longhorn
spec:
  diskSelector: []
  frontend: blockdev
  nodeSelector: []
  numberOfReplicas: 2
  size: "322122547200"
  staleReplicaTimeout: 30
---
apiVersion: longhorn.io/v1beta2
kind: Volume
metadata:
  name: pvc-31982d4c-475e-42e3-b394-124973bdda7e
  namespace: longhorn
spec:
  diskSelector: []
  frontend: blockdev
  nodeSelector: []
  numberOfReplicas: 3
  size: "21474836480"
  staleReplicaTimeout: 30
---
apiVersion: longhorn.io/v1beta2
kind: Volume
metadata:
  name: pvc-913fe3eb-997a-486d-bce7-b91bd17a3f00
  namespace: longhorn
spec:
  diskSelector: []
  frontend: blockdev
  nodeSelector: []
  numberOfReplicas: 3
  size: "8589934592"
  staleReplicaTimeout: 30
---
apiVersion: longhorn.io/v1beta2
kind: Volume
metadata:
  name: pvc-2008639f-0bbe-46d4-ba42-4f87cef3d1ea
  namespace: longhorn
spec:
  diskSelector: []
  frontend: blockdev
  nodeSelector: []
  numberOfReplicas: 3
  size: "53687091200"
  staleReplicaTimeout: 30
---
apiVersion: longhorn.io/v1beta2
kind: Volume
metadata:
  name: pvc-0d324ffa-c91e-4239-ba08-859cc9f165dd
  namespace: longhorn
spec:
  diskSelector: []
  frontend: blockdev
  nodeSelector: []
  numberOfReplicas: 2
  size: "1073741824"
  staleReplicaTimeout: 30
---
apiVersion: longhorn.io/v1beta2
kind: Volume
metadata:
  name: pvc-4c89ac47-d08d-48bf-9265-493249ecedad
  namespace: longhorn
spec:
  diskSelector: []
  frontend: blockdev
  nodeSelector: []
  numberOfReplicas: 2
  size: "21474836480"
  staleReplicaTimeout: 30
---
apiVersion: longhorn.io/v1beta2
kind: Volume
metadata:
  name: pvc-3d16299a-48d7-4b8e-963f-9c1f00e26806
  namespace: longhorn
spec:
  diskSelector: []
  frontend: blockdev
  nodeSelector: []
  numberOfReplicas: 2
  size: "1073741824"
  staleReplicaTimeout: 30
