apiVersion: v1
kind: Secret
metadata:
  name: gitea-admin-secret
  namespace: gitea
type: Opaque
stringData:
  username: <CHANGE_ME>
  password: <CHANGE_ME>
  email: <CHANGE_ME>
---
apiVersion: v1
kind: Secret
metadata:
  name: gitea-postgres-secret
  namespace: gitea
type: Opaque
stringData:
  password: <CHANGE_ME>
