apiVersion: v1
kind: ConfigMap
metadata:
  name: gitea-runner-config
  namespace: gitea
data:
  config.yaml: |
    log:
      level: info

    runner:
      labels:
        - pi
        - arm64

    container:
      require_docker: false

    cache:
      enabled: false
