apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: registry-pvc
  namespace: registry
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-cluster
  resources:
    requests:
      storage: 10Gi

#patch volume before reinstall: DATA
#kubectl patch pv pvc-f544bc01-41f8-4451-8ca7-e5b75a2a7d48 --type json -p '[{"op": "remove", "path": "/spec/claimRef/uid"}]'