apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  #storageClassName: local-path
  storageClassName: nfs-cluster
