apiVersion: v1
kind: Service
metadata:
  name: immich-server-nodeport
  namespace: immich
  labels:
    app.kubernetes.io/instance: immich
    app.kubernetes.io/name: server
spec:
  type: NodePort
  ports:
    - port: 2283
      targetPort: http
      protocol: TCP
      name: http
      nodePort: 30009
  selector:
    app.kubernetes.io/controller: main
    app.kubernetes.io/instance: immich
    app.kubernetes.io/name: server
